name: CI Build App

on:
  push:
    branches: [main]
    paths:
      - 'build/src/**'
  workflow_dispatch:

jobs:
  test:
    name: 'Tests & Linting'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

       # Add the pip install command here
      - name: 'Install Python dependencies'
        run: pip install -r build/requirements.txt
        
      - name: 'Install pylint'
        run: pip install pylint

      - name: 'Run linting'
        run: pylint build/src

      - name: 'Run tests'
        run: pytest build/src

  build:
    name: 'Build & Deploy Image'
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      # Nicer than using github runid, I think,it will be picked up automatically by make
      - name: 'Create datestamp image tag'
        run: sudo echo "IMAGE_TAG=$(date +%d-%m-%Y.%H%M)" >> $GITHUB_ENV

      - name: 'Docker build image'
        run: make image

  deploy:
    name: 'Deploy to Droplet'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: 'Copy Docker image to droplet'
        run: ssh root@161.35.78.56 "docker stop webapp_container"

      - name: 'Copy Docker image to droplet'
        run: scp webapp/build root@161.35.78.56 .

      - name: 'Load Docker image on droplet'
        run: ssh root@161.35.78.56 "docker load -i /webapp/build/image.tar"

      - name: 'Restart container on droplet'
        run: ssh root@161.35.78.56 "docker start webapp_container"
