name: CI Build App

on:
  push:
    branches: [main]
    paths:
      - 'build/src/**'
  workflow_dispatch:

jobs:
  test:
    name: 'Tests & Linting'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

       # Add the pip install command here
      - name: 'Install Python dependencies'
        run: pip install -r requirements.txt

      - name: 'Run tests'
        run: pytest build/src/app || true
        #continue-on-error: true

      # Install Flake8 for linting
      - name: 'Install Flake8'
        run: pip install flake8

      # Run Flake8 with custom configuration
      - name: 'Run Flake8'
        run: |
          flake8 --max-line-length=100 --ignore=E203,E266,E501,W503 --exclude=.git,__pycache__,docs/source/conf.py,old,build,dist src/ || true

      - name: 'Install pylint'
        run: pip install pylint

      - name: 'Run linting'
        run: pylint build/src/app || true
        continue-on-error: true

       # Run Pylint with custom configuration
      - name: 'Run Pylint'
        run: |
          pylint --max-line-length=100 --disable=missing-docstring src/app || true

  build-and-push:
    name: 'Build & Push Docker Image'
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Print current directory
        run: pwd

      - name: Verify directory structure
        run: ls -l build/src/app

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t engelat/webapp:latest .
          docker push engelat/webapp:latest

  deploy:
    name: 'Deploy to Droplet'
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
    - name: 'Set up SSH'
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy Webapp
      run: |
        echo "SSH key: $SSH_KEY"
        chmod 400 $SSH_KEY
        ssh -o StrictHostKeyChecking=no -i $SSH_KEY root@161.35.78.56 "\
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }} && \
          docker pull webapp:latest && \
          docker ps -aq | xargs -r docker stop | xargs -r docker rm && \
          docker run -d -p 5000:5000 webapp:latest"
