name: CI Build App

on:
  push:
    branches: [main]
    paths:
      - 'build/src/**'
  workflow_dispatch:

jobs:
  test:
    name: 'Tests & Linting'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Run linting'
        run: make lint

      - name: 'Run tests'
        run: make test-report

      - name: 'Upload test results'
        uses: actions/upload-artifact@v2
        # Disabled when running locally with the nektos/act tool
        if: ${{ always() && !env.ACT }}
        with:
          name: test-results
          path: ./test-results.xml

      - name: 'Publish test results'
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: ${{ always() && !env.ACT }}
        with:
          files: test-results.xml

  build:
    name: 'Build & Deploy Image'
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      # Nicer than using github runid, I think,it will be picked up automatically by make
      - name: 'Create datestamp image tag'
        run: sudo echo "IMAGE_TAG=$(date +%d-%m-%Y.%H%M)" >> $GITHUB_ENV

      - name: 'Docker build image'
        run: make image

  deploy:
    name: 'Deploy to Droplet'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: 'Copy Docker image to droplet'
        run: ssh root@161.35.78.56 "docker stop webapp_container"

      - name: 'Copy Docker image to droplet'
        run: scp webapp/build root@161.35.78.56 .

      - name: 'Load Docker image on droplet'
        run: ssh root@161.35.78.56 "docker load -i /webapp/build/image.tar"

      - name: 'Restart container on droplet'
        run: ssh root@161.35.78.56 "docker start webapp_container"
